### ISSUE TITLE
Managed wiki instead of repo

### ISSUE THREAD

**Issue by jschreuder** [fuel/docs#1]
Wouldn't it be a better idea to start documentation as a managed wiki? Managed in the way that you only allow a few known developers to directly change anything and allow for everyone else to submit changes to the docs? That way it's a lot easier and faster to create documentation for anyone who wants to contribute, but doesn't have Git figured out yet.

Speaking for myself, I'd edit a wiki fast in between other stuff if I'd notice an error. But to contribute to Github would take me just that much longer that I'd postpone editing and most likely will forget what & why I thought an edit was needed.

**Comment by philsturgeon** [comment]
Wiki's are generally of a very low quality. The people most likey to fork the documentation are people who are currently forking and contributing code to the core. If you can contribute code then you'll have no problem contributing HTML :)

If anybody else does it, then even better. This way we have the option of having others contribute documentation and we still get to review it before it goes into the core.

**Comment by jschreuder** [comment]
I completely agree with you that most wiki's suck. Which is why I didn't suggest a normal open wiki but a managed one that does allow for free editing but only shows what has been edited by the allowed developers or has been approved by any of them.

The thing is that many docs contain a lot of very small mistakes that can be confusing for beginners. When a beginner finds one of those, probably any of them will manage to edit a proposal for the wiki - but very few will manage or think about creating a git fork editing and pushing.

I won't mind and it's not that much harder for any developer, it just is a little to high a threshold to comment for many startup users and it takes just that little bit longer that small edits might be postponed and forgotten by the more experienced ones.

You won't have the power of forks, merges and such - but if I remember correctly MediaWiki for instance does offer a little functionality like that when entries are locked.

A last advantage (IMO) is that you limit how much freedom people have with HTML by using simplified markup language and as such you won't have any trouble updating a design at a later date.

**Comment by dhrrgn** [comment]
We have thought about this hard, and to be honest the main reason fro having the docs in a repo is so that the docs are downloadable for offline use.  A Wiki does not provide this.  Closing the issue.

Dan
