### ISSUE TITLE
Russian translate?

### ISSUE THREAD

**Issue by SCIF** [fuel/docs#118]
What do you think about translating docs on another language? I translated any pages on russian and want to complete translate all docs.

**Comment by SCIF** [comment]
I've started publishing translate — http://scif.in-res.ru/fuel/docs/index.html
And i suggest add to all pages any switch for switching language, like in left top corner there — http://avisynth.org.ru/docs/russian/index.htm
It can be wrote in jQuery and include in nav.js file. That helps avoid unnecessary editing every page.

**Comment by SCIF** [comment]
I  wrote it :D

Examples:
http://scif.in-res.ru/fuel/docs/en/
and
http://scif.in-res.ru/fuel/docs/ru/

**Comment by frankdejonge** [comment]
The official docs are and will be in English. You are free to translate distribute it any way you like as the docs are licensed under MIT.
