### ISSUE TITLE
Change of parameter documentation format

### ISSUE THREAD

**Issue by WanWizard** [fuel/docs#123]
When going through the docs, I notice some pages where the 'default' column defines the default value of the parameter, and other define the type.

Should we not define both (i.e. add an extra column) because I feel both are relevant when documenting the method.

**Comment by frankdejonge** [comment]
I think defining both is the way to go. Although you'll get a lot of 'mixed' values, it does clear things up. And it helps to get a unified method doc template.

**Comment by WanWizard** [comment]
I would suggest postponing this to 2.0, since we need to rework the docs for that version anyway.
