### ISSUE TITLE
Include procedural shortcuts in docs

### ISSUE THREAD

**Issue by jschreuder** [fuel/docs#135]
- logger() should be mentioned with the Log class
- __() should be mentioned alongside Lang::line()
- e() should be mentioned with Security::htmlentities() and on the Security page
- array_to_attr() and html_tag() should be mentioned with the HTML class somewhere
- in_arrayi() should be mentioned with the Arr class
- render() should be mentioned with the View class/general docs

https://github.com/fuel/core/blob/master/base.php

**Comment by frankdejonge** [comment]
Documented it all, logger function may change but is covered for now.
