### ISSUE TITLE
Where to put Request404Exception()?

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/docs#185]
I understand this is how to throw a 404 error:

```
throw new Request404Exception();
```

But nowhere in the Docs is this explained – where should it go?

**Comment by WanWizard** [comment]
I think the most logical place is General, 404 handling.

**Comment by zoe-edwards** [comment]
Will add it in but I’ve got an open pull request stopping me. Who does the pull requests now?

**Comment by WanWizard** [comment]
This one you mean? https://github.com/fuel/docs/pull/184. It says it can not be merged, probably due to a conflict with an earlier merge.

**Comment by zoe-edwards** [comment]
I wish it would tell me that! Do you know if it actually conflicts? I just wanted to add in a note about the fact show_404() won’t work anymore – everybody is going to get pretty annoyed when they’ve got to back and replace them all.

**Comment by WanWizard** [comment]
You closed it, so I can't see it anymore. But yes, github gave the error "this pull request can not be merged automatically", which usually means there's a merge conflict.
