### ISSUE TITLE
Make header fixed and remove the scrollTo thing which happens on expanding Nav

### ISSUE THREAD

**Issue by kapv89** [fuel/docs#231]
I tried doing it .. but can't find the exact places where code needs to be changed. Doing the thing mentioned in title makes the nav always remain there on screen and makes it easy to switch b/w docs for different sections

**Comment by dhrrgn** [comment]
We had this at one point, but believe us, it is more annoying than you would think.  The main problem is on small screens.  some times, once it is open if you expand all the menus and such, you could "lose" the TOC handle below the screen.

We wont be doing this.
