### ISSUE TITLE
forge instead factory on docs

### ISSUE THREAD

**Issue by orgos** [fuel/docs#239]
seeing the official docs I found View::factory on some examples, when using it the log files say to use View::forge because factory its deprecated...

**Comment by ushis** [comment]
@orgos The official docs are written for FuelPHP 1.0, where factory() is used. Read the dev docs if you use 1.1: http://fuelphp.com/dev-docs/

**Comment by frankdejonge** [comment]
the docs for 1.1 are currently on http://fuelphp.com/dev-docs/

**Comment by orgos** [comment]
really thanks
