### ISSUE TITLE
Fuel::DEVELOP or Fuel::DEVELOPMENT

### ISSUE THREAD

**Issue by bproctor** [fuel/docs#252]
In general/environments.html, it refers to Fuel::DEVELOP, but in the code it is Fuel::DEVELOPMENT

**Comment by tom-phpgenie** [comment]
I believe the correct one is `Fuel::DEVELOPMENT`

**Comment by WanWizard** [comment]
https://github.com/fuel/docs/issues/257 should have closed this one too...
