### ISSUE TITLE
Search Returns No Results

### ISSUE THREAD

**Issue by tomschlick** [fuel/docs#277]
I am guessing this is due to the changeover from fuelphp.com/docs to docs.fuelphp.com. I would guess that it is a setting within the custom search as I couldn't find any mention of such path in the js.

**Comment by zoe-edwards** [comment]
It’s powered from Google’s end using their [Custom Search Engine](http://www.google.com/cse/) – however created it would need to edit it, ideally.

**Comment by zoe-edwards** [comment]
This hasn’t been fixed yet and is really quite annoying. Can we sign up for a new one and get this pushed through?

**Comment by kenjis** [comment]
You're right, this bug has not been fixed. Hope quick fix.

**Comment by WanWizard** [comment]
This has been fixed in the mean time...

**Comment by zoe-edwards** [comment]
Thanks again!
