### ISSUE TITLE
Development branch documentation

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/docs#298]
There’s a (broken) link the Development Branch Documentation at the bottom of http://docs.fuelphp.com/. Is there still a development version?

Also, how often does the Docs update – I had a pull request accepted on January 6th for a feature that is in 1.1 so should be in the Docs now.

**Comment by WanWizard** [comment]
At the moment there isn't, it disappeared when we moved to pagodabox.

@dhorrigan, any progress on this?

**Comment by WanWizard** [comment]
The docs on docs.fuelphp.com are the official release docs. So they are only updated from the develop branch when we release a new version.

**Comment by zoe-edwards** [comment]
But, for example, I wrote that page on Markdown, which is a 1.1 feature – that should be in the Docs now. You’ve just told me about the `-env` command line option for Oil (thanks!), which I assume is in 1.1, but I can’t find any notes about in the Docs. I’ll gladly update the Docs to accommodate all these hidden features, but if they don’t appear on the public site until 1.2, it’s not that useful to the average Joe learning FuelPHP!

Edit: That part of Oil is not a 1.1 feature I’ve just discovered.

**Comment by WanWizard** [comment]
1.1/master of Fuel/Docs has been created on December 13, 2011. This is the repository that is the public docs site, and is created at the same time that repo is created for the code repositories.

It could well be (Markdown is an example) that code was included in the repo before that date, but not documented. If it is documented after that date (again, see Markdown) then the code is part of 1.1/master (official release v1.1), but the docs aren't.

It is way to much work to check with every commit and/or pull request to see if this is a change that needs to be backported to older repositories, and update the corresponding downloads and websites.

Instead, it should be the rule (and we should enforce that) that no code is accepted if not properly documented. You'll see that for most commits I do, there is a corresponding commit to the docs (see for example the recent Theme and Asset changes).

**Comment by WanWizard** [comment]
@dhorrigan when you have the time, could you get dev docs and the api back online?

Also, the google search doesn't work anymore on docs, probably due to an cse settings issue. How has the Google account and can check this out? @FrenkyNet ?

**Comment by WanWizard** [comment]
Development docs are up again, on the different host for the time being. They can be accessed through the link on the homepage of the docs, or in the header of the fuelphp website.

**Comment by zoe-edwards** [comment]
Thanks!
