### ISSUE TITLE
(Classes) Unzip missing

### ISSUE THREAD

**Issue by billmn** [fuel/docs#358]
The Unzip class is not documented ... does exists a reason?

**Comment by WanWizard** [comment]
Yes, two. 

There's a core issue open for a rewrite of the class, and nobody has documented it yet (probably because of that open issue).

**Comment by kenjis** [comment]
https://github.com/fuel/core/issues/287

It is going to 2.0.

What do we do in 1.x?

**Comment by WanWizard** [comment]
If you can find the time to document it, be my guest. Given the rewrite it's low prio for us at the moment.
