### ISSUE TITLE
PHPUnit config / Unit testsing Docs

### ISSUE THREAD

**Issue by dhrrgn** [fuel/docs#38]
**Entered by Eric Barnes on 4/8/11**

The paths in the phpunit bootstrap and xml file are hardcoded and if you change your app path the unit tests will no longer run.

```
$app_path        = '../app/';
$package_path    = '../fuel/packages/';
$core_path        = '../fuel/core/';

$ php oil test

Warning: require_once(/bootstrap.php): failed to open stream: No such file or directory in /Users/Sites/fuel/oil on line 33

Fatal error: require_once(): Failed opening required '/bootstrap.php' (include_path='.:/usr/lib/php') in /Users/Sites/fuel/oil on line 33
```

**Wan Wizard Responded**

Correct, you'll have to update these as you have to update your index.php.

There are no docs yet for unit tests, I'll leave this ticket open because this needs to be documented.

**Comment by cmillr** [comment]
As of the merge of #340, there is now a Unit Testing page in the documentation!

**Comment by aronrosenberg** [comment]
This can be closed now with the recent pull request and 'test' documentation.
