### ISSUE TITLE
Database Introduction has misleading information on database configuration.

### ISSUE THREAD

**Issue by keevitaja** [fuel/docs#428]
http://docs.fuelphp.com/classes/database/introduction.html

/ ---- /
In order to begin working with databases, you must change the database settings. The database config file is located at **APPPATH/config/db.php**. 
/ ---- /

it should be **APPPATH/config/(development|production)/db.php** and example code is wrong as well.

**Comment by WanWizard** [comment]
This has been corrected in the 1.4/develop docs.
