### ISSUE TITLE
cURL request

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/docs#491]
I can’t find any docs about the cURL driver in the Request class? (Reminder to self to write some.)

**Comment by kenjis** [comment]
http://fuelphp.com/docs/classes/request/curl.html

**Comment by zoe-edwards** [comment]
Oh wait it’s a driver, but here’s the confusion:

http://fuelphp.com/dev-docs/classes/request/request.html

```
forge($uri = null, $route = true)
```

But it’s actually:

```
forge($uri = null, $options = true, $method = null)
```

And options includes the ability to use a driver, I asume that

```
Request::forge($url, 'curl', 'post');
```

Would create a POST cURL request?

**Comment by WanWizard** [comment]
That assumption is correct.

**Comment by zoe-edwards** [comment]
Great, can we leave this open, I might have some time to go through this and the other two soon.
