### ISSUE TITLE
(Classes) Log has gone, maybe need to add the document of Log Package?

### ISSUE THREAD

**Issue by indigofeather** [fuel/docs#495]
Since v1.5 had removed Log class, but the document was not changed, perhaps it will make new user confused.

**Comment by WanWizard** [comment]
The class has been removed, but replaced by the package (which is required, the core uses it), and the API of the log class has not changed. So the docs are still valid.

In 1.6 the Log class will return in the core, but as a facade for the monolog package. Expect other classes to be transformed like this as well. For the application, it is transparent.

**Comment by indigofeather** [comment]
Thank you for your explanation. lol
