### ISSUE TITLE
Asset::get_file mismatch between required parameters and example

### ISSUE THREAD

**Issue by knitinr** [fuel/docs#513]
The Asset::get_file function specification indicates that the file and the type parameters are required. However, the example provided has only the file parameter specified.

![FP_DocBug_AssetGetFile](https://f.cloud.github.com/assets/2382987/166174/55cc09fc-798e-11e2-9379-1dd349edb389.png)

**Comment by danielrodriguezac** [comment]
Please turn it into a pull request :)

**Comment by WanWizard** [comment]
$type is required. the example is wrong. It should be

```
echo Asset::get_file('jquery.js', 'js');
```
