### ISSUE TITLE
Typo in EAV example: Semicolon instead of comma

### ISSUE THREAD

**Issue by knitinr** [fuel/docs#518]
The $_eav array declaration of the Patient class has a semicolon, where most likely a comma was intended.

Actual:
    protected static $_eav = array(
        'statistics' => array(      // we use the statistics relation to store the EAV data
            'attribute' => 'key',   // the key column in the related table contains the attribute
            'value' => 'data',      // the data column in the related table contains the value
        );
    );

Expected:
    protected static $_eav = array(
        'statistics' => array(      // we use the statistics relation to store the EAV data
            'attribute' => 'key',   // the key column in the related table contains the attribute
            'value' => 'data',      // the data column in the related table contains the value
        ),
    );

**Comment by WanWizard** [comment]
I don't see that semicolon, so it looks like it's already fixed.

edit: in #519
