### ISSUE TITLE
Mention in Installation instructions that oil is a part of the application

### ISSUE THREAD

**Issue by ipsod** [fuel/docs#569]
Not knowing that oil was a configurable part of the application caused me some debugging grief.  I think this is something fairly major that should be configured at installation.  I think it should also be mentioned in the Oil intro page, but don't know which page should reference the other.

**Comment by WanWizard** [comment]
What exactly is configurable about oil? I wouldn't know, never did anything.

**Comment by ipsod** [comment]
Specifically, DOCROOT.  DOCROOT changes when running Tasks, which breaks a function in \Fuel\Core\Email and makes DOCROOT a useless, changing "constant," so that either it must be modified or a new constant created if one wants to reference /path/to/fuel/public.

**Comment by WanWizard** [comment]
DOCROOT is defined as "the location of the front controller". Which is different for oil and index.

The Email package doesn't use DOCROOT, other then as a default asset location, which is a config item that is documented.

It will not be changed, it will break everything out there that currently uses it like this.

**Comment by ipsod** [comment]
So, should I make a new config item or constant to refer to /path/to/public, or is there already a way to do this?

Also, you're contradicting yourself:
https://github.com/fuel/oil/issues/158
https://github.com/fuel/core/issues/821

**Comment by WanWizard** [comment]
Exactly where? 

I'm just saying we will not change it, at least not in the 1.x release train, for compatibility reasons. But as per my earlier remark, if you need it changed, feel free to do so. 

A quick scan shows that only Asset and Theme use DOCROOT internally, both to access public assets. So for the framework it should not be a problem if you want it to point to your public folder.

**Comment by ipsod** [comment]
I see.  Thank you.
