### ISSUE TITLE
oil refine migrate --version=0 migrates to latest version

### ISSUE THREAD

**Issue by kurtmilam** [fuel/docs#57]
Steps to reproduce:
1. Create two migrations (001 & 002).
2. Refine to the latest Migration:
   $ php oil refine migrate
   Migrated to latest version: 2.
3. Refine to Migration 0:
   $ php oil refine migrate --version=0
   Error: Could not migrate to latest version, still using 2.
4. Refine to Migration 1:
   $ php oil refine migrate --version=1
   Migrated to version: 1.
5. Refine to Migration 0:
   $ php oil refine migrate --version=0
   Migrated to latest version: 2.

Not huge, but it would be nice to be able to go back to 0 using oil.

**Comment by philsturgeon** [comment]
Hey, thanks for reporting this. I've got it working now, but this issue should have been raised on fuel/core instead of fuel/docs. :)

**Comment by kurtmilam** [comment]
Yeah, crazy - I searched around in fuel/core for my report for about 20
minutes last night. I thought I'd reported in core but was stumped when I
couldn't find it there. So, mystery solved. No idea how/why I reported in
docs - simple oversight on my part :-)

Really enjoying working with Fuel, so far - you guys have done a fantastic
job - feels super clean and very easy to wrap my head around.
