### ISSUE TITLE
General/Routing bad example

### ISSUE THREAD

**Issue by nakp** [fuel/docs#66]
the "slightly advanced routing" makes reference to a 'routes' array just like

``` php
<?php
'routes' => array(
    'blog/(:any)'      => 'blog/entry/$1' //and so on...
);
```

which makes you think all your custom routes have to be placed under that 'specific' array, inside of the array returned in routes.php config file

It made me test like carzy! and solution was so easy ¬¬

**Comment by frankdejonge** [comment]
This is now fixed, thanks!
