### ISSUE TITLE
(General) Security

### ISSUE THREAD

**Issue by jschreuder** [fuel/docs#67]
There needs to be an overview of all the security measures Fuel offers.

**Comment by jschreuder** [comment]
I just added a mostly empty page with the following topics:
- _Output encoding_ - this should explain why output encoding is safer than input filtering and how it's  employed by the View & ViewModel classes
- _CSRF protection_ - should have usage examples of the security class methods and config tips
- _XSS filtering_ - should mostly point to the method in the security class & HTMLawed which we use for that
- _Input filtering_ - should explain how to config Fuel to employ input filtering
- _SQL injection_ - should explain how the DB query builder prevents that (and note the Orm uses it and is secure as well)

**Comment by WanWizard** [comment]
started working on this...
