### ISSUE TITLE
Is cell docs page missing?

### ISSUE THREAD

**Issue by watilde** [fuel/docs#689]
Hi. I tried to check `oil cell` command then I saw a docs URL, but it seems 404.
Is cell docs page missing? http://docs.fuelphp.com/packages/oil/cell.html

cli history:

```
$ oil cell

Usage:
  oil cell <sub-command> <cell-name>

Description:
  Packages containing extra functionality can be downloaded (or git cloned) simply with
  the following commands.

Runtime options:
  --via-zip       # Download a ZIP file instead of using Git or Hg.

Examples:
  oil cell list
  oil cell search <keyword>
  oil cell show <cell-name>
  oil cell install <cell-name>
  oil cell uninstall <cell-name>

Documentation:
  http://docs.fuelphp.com/packages/oil/cell.html
```

Thanks.

**Comment by WanWizard** [comment]
cells was an old idea to introduce a central package repository, which never really materialized, so the idea was scrapped. It should have been removed fro the code too, but I think nobody was too bothered.

In the meantime the world moved on, and gave us Composer and Packagist, so it isn't really needed anymore. We've got some other ideas for Fuel v2, we'll which ones will make it off the drawing board.
