### ISSUE TITLE
Dead link to crypt class

### ISSUE THREAD

**Issue by Art4** [fuel/docs#691]
In http://fuelphp.com/docs/ the [url to the Core/Crypt class](http://fuelphp.com/docs/classes/crypt.html) returns a 404 error.

In [dev-docs](http://fuelphp.com/dev-docs/) there is a submenu under Core/Crypt. I don't know, how to fix this.

**Comment by kenjis** [comment]
I see submenu under Core/Crypt in /docs/.
Is it fixed?

**Comment by WanWizard** [comment]
So do I. Problem with a cached js file perhaps?

**Comment by Art4** [comment]
Oh. Cache cleared and Problem solved. :smile: Sorry
