### ISSUE TITLE
Migrate Class Documentation Does Not Show Correct Return Types

### ISSUE THREAD

**Issue by willpoorman** [fuel/docs#742]
The documentation states that Migrate::latest() should return a bool, yet reading the actual implementation, it shows that it returns what is returned from running Migrate::version() which in turn returns what is returned from Migrate::run() which appears to always return an array that contains one entry that is either the number of the version migrated to or false if it is already at the latest version.

So the return type listed for version() is misleading as it is mixed but it is returned as an array and thus so is latest()

**Comment by WanWizard** [comment]
Thanks, we'll have a look.
